// CHANDRA — Content Architecture
// Separates confirmed brand content from placeholder metrics/copy for client verification.

export const siteContent = {
  brand: {
    name: 'CHANDRA',
    deltaChar: 'Δ', // Geometric stylized delta: CHANDRΔ
    tagline: 'EVENTS BEYOND ORDINARY', // [Placeholder / To be confirmed]
    idea: 'EVENTS THAT MOVE PEOPLE',
    pillars: 'IDEAS · PRODUCTION · EXPERIENCES',
  },
  navigation: [
    { label: 'ABOUT', href: '#about' },
    { label: 'WORK', href: '#work' },
    { label: 'SERVICES', href: '#process' },
    { label: 'CONTACT', href: '#contact' },
  ],
  hero: {
    eyebrow: 'EVENTS THAT',
    titleLine1: 'MOVE',
    titleLine2: 'PEOPLE',
    descriptor: 'IDEAS · PRODUCTION · EXPERIENCES',
    cta: "LET'S CREATE →",
    verticalMeta: ['PEOPLE', 'IDEAS', 'SPACES', 'EXPERIENCES'],
    backdropCaption: 'A BIGGER TOMORROW', // [Placeholder]
  },
  philosophy: {
    eyebrow: 'OUR PHILOSOPHY',
    headlineLine1: 'MORE THAN',
    headlineLine2: 'EVENTS',
    headline: 'MORE THAN EVENTS',
    subline: 'WE CREATE MOMENTS THAT MATTER',
    body: 'From the first idea to the final moment, we shape every detail around what your audience will feel, remember and talk about.',
    cta: 'SEE OUR APPROACH →',
    visualCaption: ['IDEAS', 'PEOPLE', 'EXPERIENCES'],
    microLabels: ['IDEA', 'SPACE', 'LIGHT', 'PEOPLE'],
  },
  about: {
    eyebrow: 'ABOUT CHANDRA',
    chapters: [
      {
        id: '01',
        metadata: '01 / ROLE',
        headlineLine1: 'BUILT BEHIND',
        headlineLine2: 'THE MOMENT.',
        headline: 'BUILT BEHIND THE MOMENT.',
        body: 'Creative thinking, production discipline and on-ground execution working toward one shared outcome.',
        image: '/media/about-01-role.jpg',
        imageAlt: 'Chandra production lead specialist conducting backstage venue walk-through in arena before doors open',
        objectPosition: '55% center',
        placeholder: true, // Temporary design placeholder until official production shoot assets are supplied
      },
      {
        id: '02',
        metadata: '02 / ROOTED HERE',
        headlineLine1: 'ROOTED IN TAMIL NADU.',
        headlineLine2: 'BUILT FOR SCALE.',
        headline: 'ROOTED IN TAMIL NADU. BUILT FOR SCALE.',
        body: 'Grounded in South India’s premier venues and production hubs, engineered to deliver ambitious experiences across the region and beyond.',
        image: '/media/about-02-roots.jpg',
        imageAlt: 'Chandra production crew managing on-ground stage load-in and truss alignment in arena hall',
        objectPosition: 'center 60%',
        placeholder: true,
      },
      {
        id: '03',
        metadata: '03 / CAPABILITY',
        headlineLine1: 'COMPLEXITY STAYS',
        headlineLine2: 'BEHIND THE SCENES.',
        headline: 'COMPLEXITY STAYS BEHIND THE SCENES.',
        body: 'Every cue, crew, vendor and technical detail is coordinated so the experience feels effortless to the people in the room.',
        image: '/media/about-03-capability.jpg',
        imageAlt: 'Master lighting and timecode show-control console in operation behind the scenes',
        objectPosition: 'center 40%',
        placeholder: true,
      },
      {
        id: '04',
        metadata: '04 / PEOPLE',
        headlineLine1: 'EXPERIENCE BEHIND',
        headlineLine2: 'EVERY DETAIL.',
        headline: 'EXPERIENCE BEHIND EVERY DETAIL.',
        body: 'The people behind the show bring creative, technical and operational decisions together.',
        image: '/media/about-04-people.jpg',
        imageAlt: 'Chandra technical directors and production coordinators on stage during technical verification',
        objectPosition: '40% center',
        placeholder: true,
        verifiedStats: [], // Ready for verified proof metrics once client provides audited business indicators
      },
      {
        id: '05',
        metadata: '05 / EXPERIENCE',
        headlineLine1: 'WHAT REMAINS',
        headlineLine2: 'IS THE EXPERIENCE.',
        headline: 'WHAT REMAINS IS THE EXPERIENCE.',
        body: 'The event ends. What people felt and remember is what stays.',
        image: '/media/about-05-experience.jpg',
        imageAlt: 'Live keynote arena audience captivated under warm champagne gold illumination at experience climax',
        objectPosition: 'center 45%',
        placeholder: true,
      },
    ],
  },
  featured: {
    eyebrow: 'FEATURED EXPERIENCE',
    title: 'A Global Product Launch', // Restored for CaseStudyModal compatibility
    introHeadlineLine1: 'Selected Experiences',
    introHeadlineLine2: 'That Move Audiences',
    introSupport: 'A curated look at the kinds of events Chandra designs, produces and delivers.',
    caseStudySummary: {
      client: 'Global Automotive Pioneer',
      location: 'Main Arena, Tech Expo',
      scope: 'Keynote, Stage Architecture, 360° Reveal, Broadcast',
      description: 'A milestone product unveil uniting 3,000 in-person industry leaders and over 1.2M live-stream viewers worldwide with choreographed robotic lighting and motorized silk unveil mechanics.',
    },
    showcase: [
      {
        id: 'corporate',
        index: '01 / 05',
        category: 'CORPORATE EVENTS',
        title: 'MOMENTS BUILT FOR CONFIDENCE',
        description: 'Clear, polished experiences that put the message and audience first.',
        image: '/media/showcase_corporate_1789534391216.jpg',
        imageAlt: 'Large premium corporate keynote event in a contemporary convention venue with sophisticated stage architecture',
        isPlaceholder: true,
      },
      {
        id: 'product',
        index: '02 / 05',
        category: 'PRODUCT LAUNCHES',
        title: 'THE REVEAL BECOMES THE MOMENT',
        description: 'Launch environments designed to turn anticipation into attention.',
        image: '/media/showcase_product_1789534405057.jpg',
        imageAlt: 'Major premium product reveal inside a dark arena with dramatic controlled spotlights',
        isPlaceholder: true,
      },
      {
        id: 'festivals',
        index: '03 / 05',
        category: 'COLLEGE FESTIVALS',
        title: 'ENERGY AT FULL SCALE',
        description: 'High-energy productions built around participation, performance and crowd momentum.',
        image: '/media/showcase_festival_1789534424072.jpg',
        imageAlt: 'Large university festival concert at peak audience energy with dynamic lighting beams',
        isPlaceholder: true,
      },
      {
        id: 'awards',
        index: '04 / 05',
        category: 'AWARD NIGHTS',
        title: 'EVERY CUE EARNS THE APPLAUSE',
        description: 'Recognition experiences where stagecraft, timing and atmosphere work together.',
        image: '/media/showcase_award_1789534435927.jpg',
        imageAlt: 'Prestigious award ceremony inside an elegant ballroom with champagne-gold lighting accents',
        isPlaceholder: true,
      },
      {
        id: 'activations',
        index: '05 / 05',
        category: 'BRAND ACTIVATIONS',
        title: 'BUILT TO STEP INSIDE',
        description: 'Immersive spaces that turn a brand idea into something people can experience.',
        image: '/media/showcase_activation_1789534449403.jpg',
        imageAlt: 'Immersive experiential brand installation inside a premium exhibition environment',
        isPlaceholder: true,
      },
    ],
  },
  experiences: {
    eyebrow: 'EVENT EXPERIENCES',
    titleLine1: 'EVERY EVENT.',
    titleLine2: 'A NEW STORY.',
    title: 'Every Event. A New Story',
    subtitle: 'DIFFERENT AUDIENCES. BIGGER POSSIBILITIES.',
    exploreCta: 'EXPLORE ALL →',
    categories: [
      {
        id: 'corporate',
        index: '01',
        title: 'Corporate Events',
        shortDesc: 'Built for attention, clarity and scale.',
        image: '/media/cat-corporate.webp',
        alt: 'Corporate keynote auditorium summit with tiered seating and atmospheric blue lighting',
      },
      {
        id: 'product',
        index: '02',
        title: 'Product Launches',
        shortDesc: 'The reveal moment, engineered for impact.',
        image: '/media/cat-product.webp',
        alt: 'Sensational product launch with vertical digital LED screen towers',
      },
      {
        id: 'festivals',
        index: '03',
        title: 'College Festivals',
        shortDesc: 'Unbridled energy and collective celebration.',
        image: '/media/cat-college.webp',
        alt: 'College cultural festival concert with hands raised and golden confetti burst',
      },
      {
        id: 'awards',
        index: '04',
        title: 'Award Nights',
        shortDesc: 'Prestige, precision and cinematic recognition.',
        image: '/media/cat-awards.webp',
        alt: 'Prestigious award night gala with backlit golden trophy sculpture on stage',
      },
      {
        id: 'activations',
        index: '05',
        title: 'Brand Activations',
        shortDesc: 'Immersive worlds where audiences connect.',
        image: '/media/cat-activations.webp',
        alt: 'Architectural brand activation gallery with illuminated typography monoliths',
      },
    ],
  },
  process: {
    eyebrow: 'HOW WE BRING IT TO LIFE',
    supportingLine: 'FROM THE FIRST BRIEF TO THE FINAL CUE.',
    steps: [
      {
        id: '01',
        title: 'CONCEPT',
        description: 'We define the idea, audience and outcome.',
        meta: '01 / 05 · IDEATION',
        image: '/media/process-concept.jpg',
        imageAlt: 'Event production creative brief and architectural arena stage drawings in design studio',
      },
      {
        id: '02',
        title: 'DESIGN',
        description: 'We shape the space, story and visual experience.',
        meta: '02 / 05 · SPATIAL & VISUAL',
        image: '/media/process-design.jpg',
        imageAlt: '3D spatial visualization and volumetric laser lighting render of arena concert stage',
      },
      {
        id: '03',
        title: 'PRODUCE',
        description: 'We turn the design into a live production.',
        meta: '03 / 05 · ENGINEERING',
        image: '/media/process-produce.jpg',
        imageAlt: 'Production crew assembling massive aluminum trussing and motorized LED lighting rig',
      },
      {
        id: '04',
        title: 'MANAGE',
        description: 'Every moving part stays coordinated behind the scenes.',
        meta: '04 / 05 · SHOW CONTROL',
        image: '/media/process-manage.jpg',
        imageAlt: 'Show caller and technical director at front-of-house master control desk',
      },
      {
        id: '05',
        title: 'DELIVER',
        description: 'Everything comes together when the audience arrives.',
        meta: '05 / 05 · LIVE EXPERIENCE',
        image: '/media/process-deliver.jpg',
        imageAlt: 'Monumental live event climax with packed cheering arena audience and golden atmospheric pyro',
      },
    ],
  },
  cta: {
    eyebrow: "LET'S CREATE",
    headlineLine1: 'Experiences',
    headlineLine2: 'People Never Forget',
    primaryButton: 'PLAN AN EVENT →',
    footerAnchorLeft: 'CHANDRA',
    footerSubLeft: 'EVENTS BEYOND ORDINARY',
    footerAnchorRight: 'BIGGER EVENTS',
    footerSubRight: 'BRIGHTER TOMORROWS',
  },
  footer: {
    copyright: '© 2024 CHANDRA. ALL RIGHTS RESERVED.',
    socials: [
      { name: 'INSTAGRAM', url: 'https://instagram.com' },
      { name: 'LINKEDIN', url: 'https://linkedin.com' },
      { name: 'YOUTUBE', url: 'https://youtube.com' },
    ],
  },
};
